### ISSUE TITLE
Which tensorflow version your chatbot run on?

### ISSUE THREAD

**Issue by StephenLee2016** [higepon/tensorflow_seq2seq_chatbot#1]
Hi, you have done a amazing project, but if this project can run on tensorflow 1.2.0?

**Comment by higepon** [comment]
Hi,
I'm running it in 1.0.1.

>>> import tensorflow as tf
>>> tf.__version__
'1.0.1'

lib/seq2seq_model.py is not running 1.1 or 1.2.
Will update it once it's updated in upstream.

thanks!
